name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - "main"
      - "development"
    paths:
      - "lambda/get_all_inventory_items/**/*"
      - "lambda/get_inventory_item/**/*"
      - "lambda/add_inventory_item/**/*"
      - "lambda/delete_inventory_item/**/*"
      - "lambda/get_location_inventory_items/**/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Zip the get_all_inventory_items Lambda function
        if: contains(github.event.head_commit.modified, 'lambda/get_all_inventory_items')
        run: |
          cd lambda/get_all_inventory_items
          zip -r function.zip .
      - name: Update Lambda function code
        run: |
          cd lambda/get_all_inventory_items
          aws lambda update-function-code --function-name get_all_inventory_items --zip-file fileb://function.zip --publish
      - name: Cleanup get_all_inventory_items zip
        run: |
          cd lambda/get_all_inventory_items
          rm function.zip
