---
name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - main
      - development

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      get_all_inventory_items: ${{ steps.filter.outputs.get_all_inventory_items }}
      get_inventory_item: ${{ steps.filter.outputs.get_inventory_item }}
      add_inventory_item: ${{ steps.filter.outputs.add_inventory_item }}
      delete_inventory_item: ${{ steps.filter.outputs.delete_inventory_item }}
      get_location_inventory_items: ${{ steps.filter.outputs.get_location_inventory_items }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check which Lambda functions changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            get_all_inventory_items:
              - lambda/get_all_inventory_items/**
            get_inventory_item:
              - lambda/get_inventory_item/**
            add_inventory_item:
              - lambda/add_inventory_item/**
            delete_inventory_item:
              - lambda/delete_inventory_item/**
            get_location_inventory_items:
              - lambda/get_location_inventory_items/**

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.get_all_inventory_items == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Zip Lambda function
        run: |
          cd lambda/get_all_inventory_items/
          zip -r get_all_inventory_items.zip .

      - name: Update Lambda function on AWS
        run: |
          cd lambda/get_all_inventory_items/
          aws lambda update-function-code \
            --function-name get_all_inventory_items \
            --zip-file fileb://./get_all_inventory_items.zip \
            --publish

      - name: Cleanup zip file
        run: |
          cd lambda/get_all_inventory_items/
          rm get_all_inventory_items.zip
